website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, send_file
from flask_login import login_required, current_user
from .models import Database
from . import db
import json
import os
import zipfile
from pathlib import Path
import time
from website.utils import get_attendance,clean_duplicate_attendance

views = Blueprint('views', __name__)

current_dir = os.path.dirname(os.path.abspath(__file__))
database_path = Path(current_dir) / Path("database")
buffer_path = Path(current_dir) / Path("buffer")
csv_path = Path(buffer_path) / Path("attendance.csv")

@views.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)

@views.route('/upload', methods=['POST', 'GET'])
@login_required
def upload_database():
    if request.method == 'POST':

        # get the name of the folder and the zip file
        folder_name = request.form['folder_name']
        zip_file = request.files['zip_file']
        
        filename, ext = os.path.splitext(zip_file.filename)
        # Check if the folder_name is empty
        if folder_name == '':
            flash('Please enter a name for the folder', category='error')
            return render_template('upload.html', user=current_user)
        
        class_in_db = Database.query.filter_by(class_name=folder_name).first()
        if not class_in_db:
            flash(f'Class "{folder_name}" does not exist.', category='error')
            return render_template('upload.html', user=current_user)
        # Check that the file is a zip file
        if ext != '.zip':
            flash('Please upload .zip files', category='error')
            return render_template('upload.html', user=current_user)
        
        new_folder_path = os.path.join(database_path, folder_name)
        os.makedirs(new_folder_path, exist_ok=True)

        zip_file.save(os.path.join(new_folder_path, f'{filename}.zip'))

        # extract and remove the first folder in the zip file
        with zipfile.ZipFile(os.path.join(new_folder_path, f'{filename}.zip'), 'r') as zip_ref:

            zip_ref.extractall(new_folder_path)


        os.remove(os.path.join(new_folder_path, f'{filename}.zip'))

      
            
        new_database = Database(class_name=folder_name, class_database_path=str(new_folder_path), user_id=current_user.id)
        db.session.add(new_database)
        db.session.commit()
        
        flash("file uploaded in class successfully", category='success')
        return render_template('upload.html', user=current_user)
              
    return render_template('upload.html', user=current_user)

@views.route('/create_new_class', methods=['GET', 'POST'])
@login_required
def create_new_class():
    if request.method == 'POST':
        class_name = request.form.get('class_name')

        folder_path = database_path / Path(class_name)
        folder_path.mkdir(parents=True, exist_ok=True)
    
        if class_name == " ":
            flash('Please enter a class name.', category='error')
            return render_template("create_new_class.html", user=current_user)
        else:
            # Assuming 'current_user' is the faculty creating the class
            new_class = Database(class_name=class_name, class_database_path=str(folder_path),user_id=current_user.id)
            db.session.add(new_class)
            db.session.commit()
            flash('Class created successfully!', category='success')
            return render_template("create_new_class.html", user=current_user)

    return render_template("create_new_class.html",user=current_user)


@views.route('/edit_class', methods=['POST', 'GET'])
@login_required
def edit_class():
    if request.method == 'POST':
        class_name = request.form['class_name']

        if not class_name:
            flash('Please enter a class name.', category='error')
            return render_template('edit_class.html', user=current_user, class_data=None)

        class_to_edit = Database.query.filter_by(class_name=class_name, user_id=current_user.id).first()

        print("class to edit :",class_to_edit)
        if not class_to_edit:
            flash(f'Class "{class_name}" does not exist.', category='error')
            return render_template('edit_class.html', user=current_user, class_data=None)

        print("Class To Edit:", type(class_to_edit))  # Debugging message

        class_data = {
            'class_name': class_to_edit.class_name,
            'class_database_path': class_to_edit.class_database_path,
        }

        print("Class Data:", class_data)  # Debugging message

        class_files = []
        if class_to_edit.class_database_path:
            class_directory_path = os.path.join(class_to_edit.class_database_path, class_name)
            if os.path.exists(class_directory_path) and os.path.isdir(class_directory_path):
                class_files = [filename for filename in os.listdir(class_directory_path) if filename.endswith('.jpg')]
                print("Class Files:", class_files)  # Debugging message
            else:
                print("Class directory not found")  # Debugging message

        class_data['class_files'] = class_files

        return render_template('edit_class.html', user=current_user, class_data=class_data)

    return render_template('edit_class.html', user=current_user, class_data=None)


@views.route('/attendance', methods=['POST', 'GET'])
@login_required
def attendance():
    if request.method == 'POST':
        start_time = time.time()
        # get the name of the folder and the zip file
        class_name = request.form['class_name']
        image = request.files['class_image']
        attendance_date = request.form['attendance_date']  # Get the selected attendance date
        csv_path = Path(buffer_path) / Path(class_name+"attendance.csv")

        
        file_name, ext = os.path.splitext(image.filename)
        print(ext)
        # Check if the class_name is empty
        if class_name == '':
            flash('Please enter a name for the folder', category='error')
            return render_template('attendance.html', user=current_user)
        
        #Check that the file is a zip file
        # if ext != '.jpg':
        #     flash('Please upload .jpg / .jpeg / .png files', category='error')
        #     return render_template('attendance.html', user=current_user)

        image_save_path = os.path.join(buffer_path, f'{file_name}{ext}')  # Use os.path.join
        image.save(image_save_path)
        row = Database.query.filter_by(class_name=class_name).first()

        if row:
            if row.user_id == current_user.id:
                database_path = row.class_database_path
                # print("Database Path:", database_path)  # Add this line for debugging
            else:
                flash('No {class_name} database available', category='error')
                return render_template('attendance.html', user=current_user)
        else:
            flash('No {class_name} database available', category='error')
            return render_template('attendance.html', user=current_user)
        print("Image_save:",image_save_path)
        
        output = get_attendance(image_save_path, database_path, True, csv_path,attendance_date)
        clean_duplicate_attendance(csv_path,attendance_date)
        end_time = time.time()
        execution_time = (end_time-start_time)/60
        print(f"Execution Time: {execution_time:.2f} minutes")
        try:
            return redirect(f"/download_csv/{class_name}")
        except:
            flash('Something went wrong', category='error')
            return render_template('attendance.html', user=current_user)
    return render_template('attendance.html', user=current_user)

@views.route('/download_csv/<class_name>')
@login_required
def download_csv(class_name):
    csv_file_path = os.path.join(buffer_path, f"{class_name}attendance.csv")
    return send_file(csv_file_path, as_attachment=True, download_name=f"{class_name}attendance.csv")

# def download_csv(class_name):
#     return send_file(csv_path, as_attachment=True)




website/templates/attendance.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">
    <script src="{{ url_for('static', filename='js/tweet.js') }}"></script>

{% endblock %}

{% block title %}Home{% endblock %} 
{% block content%}
<body>
    <div class="form-group">
        <h1>Attendance</h1>
        <form action="/attendance" method="POST" enctype="multipart/form-data">
            <label for="class_name">Class Name:</label>
            <input type="text" name="class_name"><br><br>
            <label for="class_image">Class Image:</label>
            <input type="file" name="class_image"><br><br>
            <label for="attendance_date">Attendance Date:</label>
            <input type="date" name="attendance_date"><br><br>
            <label for = "alert">Please select the date </label>
            <input type="submit" class= "btn btn-primary" value="Get Attendance">
        </form>

    </div>
</body>
    

    {% endblock %}
    

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <header>
      <div class="logo">
        <a href="/">
          <img src="{{ url_for('static', filename='images/white_logo.png') }}" alt="logo" >
        </a>
        <a href="/">
          <span class="logo-text">ClassVision</span>
        </a>
      </div>
      <div class="nav-links">
        <nav>
          <ul>
            {% if user.is_authenticated %}
              <!-- Common links for all authenticated users -->
              {% if user.usertype != 'faculty' %}
                <li><a class="nav-item nav-link" href="/upload">Upload</a></li>
              {% endif %}
              
      
              <!-- Additional links for faculty -->
              {% if user.usertype == 'faculty' %}
                
                <li><a class="nav-item nav-link" href="/create_new_class">Create New Class</a></li>
                <li><a class="nav-item nav-link" href="/attendance">Attendance</a></li>
                <li><a class="nav-item nav-link" href="/edit_class">Edit Class</a></li> <!-- Add this line -->
              {% endif %}
              <li><a class="nav-item nav-link" href="/logout">Logout</a></li>
            {% else %}
              <!-- Links for not logged in users -->
              <li><a class="nav-item nav-link" href="/login">Login</a></li>
              <li><a class="nav-item nav-link" href="/sign-up">Sign Up</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </header>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show flashmsg" role="alert">
      {{ message }}
      <button type="button" class="close msgbtnstyle" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show flashmsg" role="alert">
      {{ message }}
      <button type="button" class="close msgbtnstyle" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/create_new_class.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">

{% endblock %}

{% block title %}Create New Class{% endblock %}

{% block content %}
<div>
  <h1>Create a New Class </h1>
  <form method="POST" action="/create_new_class">
    <label for="class_name">Class Name:</label>
    <input type="text" id="class_name" name="class_name" required>
    <input type="submit" value="Create">
  </form>
</div>
{% endblock %}

website/templates/edit_class.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">

{% endblock %}

{% block title %}Edit class{% endblock %}

{% block content %}
<div>
  <h1>Edit Class</h1>
  <form method="POST" action="{{ url_for('views.edit_class') }}">
    <label for="class_name">Class Name:</label>
    <input type="text" id="class_name" name="class_name" required>
    <input type="submit" value="Edit">
  </form>

  {% if class_data %}
    <h3>Class Name: {{ class_data.class_name }}</h3>
    {% if class_data.class_files %}
      <h4>Files in the Class:</h4>
      <ul>
        {% for file_name in class_data.class_files %}
          <li>{{ file_name }}</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No files found in this class.</p>
    {% endif %}
  {% endif %}
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">

{% endblock %}

{% block title %}Home{% endblock %}
{% block content%}


<img src="{{ url_for('static', filename='images/ClassVision.png') }}" alt="home_logo" id="logo">
<main>
  <section id="hero">
      <div class="container">
          <h1>Say goodbye to manual attendance-taking.</h1>
          <p>Introducing Class Vision - a smart computer vision-based attendance system that uses facial recognition technology to accurately and efficiently identify students in a classroom with just a single photo, seamlessly recording their attendance.</p>
      </div>
  </section>
</main>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} 

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">

{% endblock %}

{% block title %}Login Up{% endblock %} 
{% block content %}
<body>
	<div class="form-group">
		<form method="POST">
			<h1>Login</h1>
			<label for="email">Email Address:</label>
			<input type="email" id="email" name="email" placeholder="abc@example.com" class="form-control" required>
			<label for="password">Password:</label>
			<input type="password" id="password" name="password" placeholder="Password" class="form-control"required>
			<input type="submit" class="btn btn-primary" value="Submit">
			<div class="radiobtn">
				<label class="checkbox-inline checkbtn" >
				  <input type="checkbox" value="faculty" id="faculty" name="usertype">  Faculty
				</label>
				<p class="radiomsg">(*If you faculty then check it)</p>
			  </div>
		</form>
	</div>
</body>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/form.css') }}"
/>

{% endblock %} {% block title %}Sign Up{% endblock %} {% block content %}
<div class="form-group">
  <form method="POST">
    <h1>Sign Up</h1>
    <label for="email">Email Address:</label>
    <input
      type="email"
      id="email"
      name="email"
      placeholder="abc@example.com"
      class="form-control"
      required
    />
    <label for="firstName">First Name:</label>
    <input
      type="text"
      id="firstName"
      name="firstName"
      placeholder="First Name"
      class="form-control"
      required
    />
    <label for="password1">Password:</label>
    <input
      type="password"
      id="password1"
      name="password1"
      placeholder="Password"
      class="form-control"
      required
    />
    <label for="password2">Password (Confirm):</label>
    <input
      type="password"
      id="password2"
      name="password2"
      placeholder="Confirm Password"
      class="form-control"
      required
    />
    <div class="radiobtn">
      <label class="checkbox-inline checkbtn" >
        <input type="checkbox" value="faculty" id="faculty" name="usertype">  Faculty
      </label>
      <p class="radiomsg">(*If you faculty then check it)</p>
    </div>

    <input type="submit" class="btn btn-primary" value="Submit" />
  </form>
</div>
{% endblock %}

website/templates/upload.html
{% extends "base.html" %} 

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">

{% endblock %}

{% block title %}Home{% endblock %} 
{% block content%}
    
    <h1>Upload a Zip File</h1>
    <form action="/upload" method="post" enctype="multipart/form-data">
        <label for="folder_name">Class Name:</label>
        <input type="text" name="folder_name"><br><br>
        <label for="zip_file">Zip File:</label>
        <input type="file" name="zip_file"><br><br>
        <label for = "alert">File name should be in Roll_num_name format</label>
        <input type="submit" value="Upload">
    </form>
{% endblock %}
    